## YAML Template.
---
server:
    port : 9090
spring:
   datasource:
      url: jdbc:mysql://db.bassure.guruofjava.com:3306/komali
      username: komali
      password: komali
      driver-class-name: com.mysql.jdbc.Driver
   data:
      mongodb:
         uri: mongodb://komali:komali@db.bassure.guruofjava.com/komali